### ISSUE TITLE
AiStandardSurface might be rendering thin-walled transparency when it's not supposed to

### ISSUE THREAD

**Issue by osiriswrecks** [lunadigital/btoa#10]
Need to look into this.

**Comment by osiriswrecks** [comment]
This seems to happen when lights are too hot - once they get to a certain intensity, standard surface materials appear to render semi-transparent. I don't know if this is an Arnold issue or a BtoA issue, but it needs more research.

**Comment by AlexeyAdamitsky** [comment]
Yes, I also encountered this.

**Comment by osiriswrecks** [comment]
Fixed along with issue #15
