### ISSUE TITLE
Camera: Orthographic Mode Doesn't Work

### ISSUE THREAD

**Issue by AlexeyAdamitsky** [lunadigital/btoa#107]
Blender 2.92
BtoA Dev Branch bd1cdc2
Arnold SDK 6.1.0
Windows 10 2004

Orthographic camera doesn't work in Arnold right now. Here is how it should behave on Cycles example:
![nbEf7Wy6yB](https://user-images.githubusercontent.com/64398828/112947755-e112b980-913f-11eb-819e-52dcfbca5278.gif)

When switching to Orthographic camera in Arnold the changes aren't reflected neither in 3D View nor in final render.

There is also a bug if you set the camera to Orthographic in Cycles when switched to Arnold it'll stuck in that view for 3D View. Although it'll render in Perspective mode anyway in Arnold.

P.S. I suspect other modes (except Perspective) might have issues too but I can't test them properly at the moment.

Test scene:
[Arnold_Test_Scene_Camera_Render_Region_GPU.zip](https://github.com/lunadigital/btoa/files/6227147/Arnold_Test_Scene_Camera_Render_Region_GPU.zip)

**Comment by osiriswrecks** [comment]
BtoA only supports perspective cameras at the moment. We can add this as a feature request for beta 0.5.0.

**Comment by AlexeyAdamitsky** [comment]
> 
> 
> BtoA only supports perspective cameras at the moment. We can add this as a feature request for beta 0.5.0.

It would be nice to have. There are several good use cases for this for some types of art and it will also come in handy for some test scenes I use to test current and upcoming shading nodes.
