### ISSUE TITLE
Rendering With 1px Transparent Line at Top Issue

### ISSUE THREAD

**Issue by AlexeyAdamitsky** [lunadigital/btoa#110]
Blender 2.92
BtoA Dev Branch bd1cdc2
Arnold SDK 6.1.0
Windows 10 2004

Final render output an image with 1px transparent line at the top. I think it's a new bug because I rendered other images in earlier builds and didn't see this before. It happens with any scene and/or camera.

![QJjdGqEpVR](https://user-images.githubusercontent.com/64398828/113490730-bb393c00-94d4-11eb-9f7f-b1a045e47015.gif)

**Comment by osiriswrecks** [comment]
Interesting. I have a sneaking suspicion is has to do with the recent render region implementation. If render regions are turned off it still uses the same variables to calculate cropping, but they're supposed to match the global image settings at that point. I'll look into this early this week.

**Comment by osiriswrecks** [comment]
@AlexeyAdamitsky This is ready to test. When you get a chance do you mind looking at it?

**Comment by AlexeyAdamitsky** [comment]
@osiriswrecks Yes, it looks like it's fixed with the 831bd44 update.
