### ISSUE TITLE
Camera viewport properties missing in Properties panel

### ISSUE THREAD

**Issue by osiriswrecks** [lunadigital/btoa#116]
I could have sworn they were there at one point, I think @AlexeyAdamitsky wrote this into his merge request. I can't find some of the viewport camera settings in the panel - things like "Show Limit" and related checkboxes. A handful of expected settings just seem to not be there at all.

This needs to be looked into more, I'm just posting it here so we can track it. I currently don't know if it's throwing an error or anything either.

**Comment by AlexeyAdamitsky** [comment]
@osiriswrecks Just to let you know. I am using 2.92 and the **Viewport Display** is where it should be. No issues. Maybe if you're testing on 2.93 you get the issue. I think Blender devs were messing with camera UI a bit so they might have changed something and it broke the compatibility. Just a guess but wanted to let you know.

**Comment by osiriswrecks** [comment]
This appears to just be user error here. Will close as invalid.
