### ISSUE TITLE
BtoA is Crashing Blender 2.93

### ISSUE THREAD

**Issue by AlexeyAdamitsky** [lunadigital/btoa#118]
Blender 2.93 Beta
BtoA Dev Branch bd1cdc2
Arnold SDK 6.1.0
Windows 10 2004

It just crashes Blender on launch if you have BtoA installed.

**Comment by N3BB3Z4R** [comment]
I just tested right now, it crashes automatically at the moment to fill the Arnold path inside the addon config in blender.

Blender 2.93 Stable
Arnold SDK 6.0.4.0
btoa 0.3.0-alpha

**Comment by AlexeyAdamitsky** [comment]
@N3BB3Z4R Blender broke BtoA compatibility with with 2.93. It might require to take a different approach to development of BtoA addon so it isn't broken so easily with future Blender updates. This will require some time to develop so I wouldn't hope for a fast fix and if you need to use BtoA you'll have to stay on 2.92 for now.

**Comment by osiriswrecks** [comment]
@AlexeyAdamitsky @N3BB3Z4R It's also unclear exactly what the breakage is. It could simply be API changes that need to be addressed and be an easy fix. I don't necessarily thing we need to do a complete overhaul *right now* but it's sometime to keep in mind long term. I'll find some time this week to look further into this.

**Comment by osiriswrecks** [comment]
Fix introduced in commit c1b3ec0 on `blender-2.93` branch. Ready for QA.
