### ISSUE TITLE
Add integration for Lentil

### ISSUE THREAD

**Issue by osiriswrecks** [lunadigital/btoa#132]
It would be cool for BtoA to support Arnold plugins - a popular one is Lentil (https://www.lentil.xyz/). We might only need to expose some UI parameters, but it would be great to get it working with BtoA.

**Comment by jaaypeso24** [comment]
agreed with this user.  The Lentil plugin by Zeno Pelgrims is an incredible tool for lookdev in Arnold.  I use it all the time in the Houdini integration.  He is also pretty accessible via the internet, so if theere are issues, he may be able to help.

**Comment by osiriswrecks** [comment]
Closing for now. Since opening this ticket, Lentil has gone open source and doesn't seem to be as actively maintained. If there's interest in the future I will re-examine.
