### ISSUE TITLE
IPR rendering bugs

### ISSUE THREAD

**Issue by osiriswrecks** [lunadigital/btoa#135]
- [ ] Adding/deleting materials doesn't work during render
- [ ] Adding/deleting objects doesn't work during render
- [x] Orthographic views don't work during render
- [ ] Camera view doesn't fill whole screen during render
- [ ] Changing light types during render doesn't do anything
- [ ] Window resizing kind of works but needs optimization
- [x] IPR render isn't exporting everything (ie, world is missing)
- [ ] General scene changes (like changing things in the render panel) don't update during render
- [ ] Updating displacement settings doesn't trigger re-render

**Comment by AlexeyAdamitsky** [comment]
I don't think it needs a separate issue just yet. IPR camera isn't working now in a sense that it doesn't respond to camera settings and defaults to some predefined settings. Probably some internal Arnold camera settings.

None of these settings are respected.
![image](https://user-images.githubusercontent.com/64398828/143069500-ab6dc52c-2e74-4b24-8b96-011325038b74.png)

As a result when we switch to IPR we have different camera view.

https://user-images.githubusercontent.com/64398828/143069689-243b18b5-66a2-47f5-abe0-bac7c240bdd8.mp4
