### ISSUE TITLE
Shading Bug with Standart Surface

### ISSUE THREAD

**Issue by AlexeyAdamitsky** [lunadigital/btoa#14]
Blender v2.92.1
BtoA Feature/Nodes Branch v0.0.5
Arnold SDK 6.1.0
Windows 10 2004

![265h1aoMA5](https://user-images.githubusercontent.com/64398828/107854105-ca7fff80-6e2a-11eb-9cc2-8f7213c72e27.png)

Strangle shading (1) is happening on the geometry when using low Specular Roughness for both metallic and dielectric materials (Metalness 0/1). I assume the bad shading also occur at high Specular Roughness but it's just not as visible (2) on yellow sphere.

If you rotate chrome or glossy plastic sphears the shading breaking line will also move. This gives me an idea that there might be something wrong with how geometry is imported.

Test scene file:
[Arnold_Test_Branch1.zip](https://github.com/lunadigital/btoa/files/5975926/Arnold_Test_Branch1.zip)

**Comment by osiriswrecks** [comment]
This appears to be related to how we're calculating normals on mesh export. Switching back to mesh.calc_tangents() method, because it appears to produce far superior results for what Arnold needs.
