### ISSUE TITLE
Surface Shader Wrong Default Opacity Value

### ISSUE THREAD

**Issue by AlexeyAdamitsky** [lunadigital/btoa#15]
Blender v2.92.1
BtoA Feature/Nodes Branch v0.0.5
Arnold SDK 6.1.0
Windows 10 2004

![blender_tvPVgafDoc](https://user-images.githubusercontent.com/64398828/107859824-42f7b800-6e4d-11eb-9320-98a01067f568.png)

This value is set to 0.906332 by default when new material created or shader node added in the node editor. I believe it should be 1.

**Comment by AlexeyAdamitsky** [comment]
Ok, I checked the rest of the value. They all have 0.906332 as default value which is wrong for some parameters I believe.

![image](https://user-images.githubusercontent.com/64398828/107860580-fdd58500-6e50-11eb-954b-8e23a2d356c9.png)

I'm not sure all the defaults are correct. I'm positive that **Opacity** and **Specular Color** default should be 1 though.

**Comment by osiriswrecks** [comment]
@AlexeyAdamitsky Are you using Filmic or a custom OCIO profile? I will check on my end but I have a feeling this is related to color mangement - although defaults are set to (1, 1, 1) it gets converted to whatever the OCIO profile says it should translate to...which poses an issue for things like opacity. This might explain what we're seeing in issue #10 as well.

**Comment by AlexeyAdamitsky** [comment]
@osiriswrecks I use Filmic. Yes I also think it's most likely connected to color management.

**Comment by osiriswrecks** [comment]
One potential solution could be to replace the opacity control in the node with a single float value. We'd have to convert it to a tuple behind the scenes because Arnold wants to you explicitly set the opacity for each color channel, but that's pretty trivial. Is there a situation where we'd need that level of control to begin with?

**Comment by AlexeyAdamitsky** [comment]
I don't mind such solution. Although currently I can live with the fact that I need to reset opacity setting back to 1.

If the proposed solution will compromise the power of Arnold for others who could use this setting the way it's supposed to I am not sure if it's the best solution. 

I'd much rather see proper color management implemented. I know Arnold works linearly and it may cause issues with how Blender works with colors. I know from Troy Sabotka that it's quite a mess so might be a challenge to make it work. Yet, as I said I'd much rather seed that part done right.

**Comment by osiriswrecks** [comment]
I agree. Let me look into this a bit...if I can keep the color socket that would be ideal but I don't have enough info to make a decision yet.

**Comment by osiriswrecks** [comment]
@AlexeyAdamitsky This issue should now be fixed with commit 577e0f6. Can you download and test to make sure?

**Comment by AlexeyAdamitsky** [comment]
I checked the latest branch. Yes, the opacity issue seems to be solved. I don't have problems with it anymore.
