### ISSUE TITLE
Window resizing needs optimization

### ISSUE THREAD

**Issue by osiriswrecks** [lunadigital/btoa#158]
It works...kind of. But it needs a lot of love and optimizations.

**Comment by osiriswrecks** [comment]
Window resizing is *significantly* more stable now that we've moved to the `gpu` module. Please test! @AlexeyAdamitsky

**Comment by AlexeyAdamitsky** [comment]
Yes, seems way more stable. No issues and it feels like its “time to first” speed improved. The only weird behavior I noticed is with GPU IRP. The area on the left side seems to be “stuck” and not updating. Sometimes it's right edge and bottom edge.

https://user-images.githubusercontent.com/64398828/179266296-7a9727af-3c47-4bfa-8f45-c4cb7a405f68.mp4

**Comment by osiriswrecks** [comment]
That's...interesting. Is this after you expand the size of the screen?
