### ISSUE TITLE
Constant Node Issue

### ISSUE THREAD

**Issue by AlexeyAdamitsky** [lunadigital/btoa#172]
I believe it's not a correct behavior. Constant node won't pass the latest color value if it's daisy chained. Like in this example:

https://user-images.githubusercontent.com/64398828/171192221-10397393-ba19-4d11-817a-57355c99cac9.mp4

**Tech Specs**
Blender 3.1.2
BtoA Dev Branch 
Arnold SDK 7.1.2.0
Windows 10 21H1
NVIDIA Drivers 472.12

**Comment by osiriswrecks** [comment]
@AlexeyAdamitsky This has been addressed and is ready for QA.

**Comment by AlexeyAdamitsky** [comment]
@osiriswrecks Checked it. The issues is solved now. Thank you!
