### ISSUE TITLE
Add a way to log to a file

### ISSUE THREAD

**Issue by osiriswrecks** [lunadigital/btoa#174]
We can configure Arnold to log to a file as well as the console. This would be huge for debugging and crashes.

See a simple example here:
https://docs.arnoldrenderer.com/display/A5ARP/Creating+and+Rendering+a+Scene

**Comment by AlexeyAdamitsky** [comment]
This is very useful. Although, I've learned how to use console to track Arnold's error messages the logging system is more helpful in case of more hard crashes.

One thing I was immediately confused with was that there aren't 100% clear instructions for the custom location. 
![image](https://user-images.githubusercontent.com/64398828/178483767-fe314fbe-fcf4-44ba-adeb-2d52c09aada0.png)

It's obvious that you need to point to a custom location but not 100% clear that you need to point to a file. This option allows you to leave just a folder location and not requiring you to pick a file. Also it doesn't specify what kind of file you need to create. If you don't specify a file where to write the logs to it won't do anything and throw error in the console.

I suggest two solutions for custom path:
1. Let user just to specify the location and as it's on the screenshot and the file name behind the scene. It can be “btoa.log” or whatever goes by default with the default log output path.
2. Make it clearer that user must specify the log name. Maybe there is a different Blender function that won't allow user to exit file view window until he specifies the file name and/or add a description that clearly states that you must specify the log file name. Maybe something like this: “Select the path to the btoa.log file location to keep Arnold log records. Create if doesn't exists.”

It's a bit of nitpicking but I believe the current solution for custom log path is prone to user error and might lead to some frustration.

**Comment by osiriswrecks** [comment]
I was thinking about the same thing last night. I think it makes sense to change it to a directory picker instead, because we can handle the filename internally. By default, if no path is provided it saves the log to your home directory, but for the sake of cleanliness I might also change that to an "arnold_logs" folder or something in the home directory so it's not littering the folder with log files.

**Comment by osiriswrecks** [comment]
@AlexeyAdamitsky Updated!
