### ISSUE TITLE
Assigning Materials Withing Geometry Nodes Messes Up With IPR

### ISSUE THREAD

**Issue by AlexeyAdamitsky** [lunadigital/btoa#178]
BtoA works pretty well with geometry nodes so far from my basics tests. Until you try to assign materials!

This is just a basic setup that can be replicated easily. Create any mesh object and add Geometry Nodes modifier. In the Geometry Nodes Editor simply use the Set Material node and assign the material created in Arnold Shader Editor.

![image](https://user-images.githubusercontent.com/64398828/175098854-8fa54e7c-2e39-4ae9-9575-ecaf9057b266.png)

I was pleasantly surprised but it worked as expected for final render. It doesn't work with IPR though. It gives errors.

![image](https://user-images.githubusercontent.com/64398828/175103216-a8d8113f-9035-425d-9c2a-0c9da3512c43.png)

**Debug Information**
BtoA version: Dev Brunch [6bac611](https://github.com/lunadigital/btoa/commit/6bac611bcb94844c40ae4cdfa5bfc395b43d7da4)
Blender version: 3.2
Operating system: Windows-10-10.0.19043-SP0 64 Bits
Graphics card: NVIDIA GeForce GTX 1080 Ti/PCIe/SSE2 NVIDIA Corporation 4.5.0 NVIDIA 472.12

**Comment by osiriswrecks** [comment]
I cannot reproduce this. Can you try testing on the latest `dev` branch and see if it still happens?

**Comment by AlexeyAdamitsky** [comment]
This is not the case anymore. Haven't experienced it since the bug report. I believe it's fixed in the latest versions.
