### ISSUE TITLE
None Of The Lights Can Emit Color

### ISSUE THREAD

**Issue by AlexeyAdamitsky** [lunadigital/btoa#18]
Blender 2.91.2
BtoA Dev Branch cb259ea
Arnold SDK 6.1.0
Windows 10 2004

None of the lights currently can emit any other color except pure white.
The test setup is simple. I used every light in the scene. Each light was set to emit color in accordance to the monkeys: 1. red; 2. green; 3. blue.
![image](https://user-images.githubusercontent.com/64398828/107941983-9f68ed80-6f9b-11eb-9036-85bfde352aab.png)
As you can see they don't.
![image](https://user-images.githubusercontent.com/64398828/107941820-5f096f80-6f9b-11eb-9eb7-678d4671f72e.png)

You can use my scene for tests if needed:
[Arnold_Test_Scene3_003.zip](https://github.com/lunadigital/btoa/files/5981303/Arnold_Test_Scene3_003.zip)

**Comment by osiriswrecks** [comment]
@AlexeyAdamitsky This should be fixed with commit 72433d7. Please test to confirm.

**Comment by AlexeyAdamitsky** [comment]
Yes, look good now. All currently available light types can emit colored lights. Thanks!

![image](https://user-images.githubusercontent.com/64398828/108090406-a1aa7500-708b-11eb-80d8-8ca9c9c7298b.png)
