### ISSUE TITLE
World Materials Issue

### ISSUE THREAD

**Issue by AlexeyAdamitsky** [lunadigital/btoa#180]
This is a new issue. I believe it was introduced very recently.

When you go to setup world materials now any material reference the same shading setup.

https://user-images.githubusercontent.com/64398828/178494331-cd16c9e1-6ea1-4430-b8a3-3808af012916.mp4

BtoA version: Dev Brunch f034f2b
Blender version: 3.2.1

**System Information**
Operating system: Windows-10-10.0.19043-SP0 64 Bits
Graphics card: NVIDIA GeForce GTX 1080 Ti/PCIe/SSE2 NVIDIA Corporation 4.5.0 NVIDIA 511.65

**Comment by osiriswrecks** [comment]
This is weird. I can't reproduce on my side - I can switch between world shader graphs in both 2.93 and 3.2 with no problem. Tested on CentOS and Windows 10.

Can you share your file?

**Comment by AlexeyAdamitsky** [comment]
I've been investigating this further.

If you create World Materials in a standard way where you use with +New button it works as expected. But if you then create a new material by using Duplicate button it doesn't work as it should in Blender. It behaves like an instant maybe. Pretty confusing behavior.

https://user-images.githubusercontent.com/64398828/178810797-d725c8ae-0f9a-400d-8e0f-1a132e74d331.mp4

**Comment by AlexeyAdamitsky** [comment]
This seems to be resolved.
