### ISSUE TITLE
Proporties Panels Are Populating Other Renderers Settings

### ISSUE THREAD

**Issue by AlexeyAdamitsky** [lunadigital/btoa#185]
I think we need to clean this up since it gets pretty confusing when you're working with other engines with BtoA addon active. Not all panels are localized to BtoA and stays global when switching to other renderers are global.

![image](https://user-images.githubusercontent.com/64398828/179513602-a678be3f-d225-43e3-9285-1859c3ea338f.png)

I spotted at least 4 panels from BtoA that are global.

**Comment by osiriswrecks** [comment]
I noticed this too. This should be easy to clean up for the 0.4.6 release.

**Comment by AlexeyAdamitsky** [comment]
This seems to be solved now.
