### ISSUE TITLE
Object Rotation in IPR Crashes Blender

### ISSUE THREAD

**Issue by AlexeyAdamitsky** [lunadigital/btoa#189]
Using the empty to control skydom rotation causes Blender crashing.

https://user-images.githubusercontent.com/64398828/184205135-94efef16-e2a4-4d70-9756-5d86b33eff0e.mp4

Crash log:
[arnold-2022-08-11-20-53-52.log](https://github.com/lunadigital/btoa/files/9310800/arnold-2022-08-11-20-53-52.log)

Blender 3.2.2
BtoA Dev Build 66213cf

**Comment by AlexeyAdamitsky** [comment]
It seems like trying to scale any object during IPR crashing Blender.

**Comment by AlexeyAdamitsky** [comment]
I can say for sure now that the issue is not isolated to the skydome rotation only. It's a global issue. Rotating any object while in IPR mode will cause the crash.

**Comment by osiriswrecks** [comment]
Although there are still some IPR bugs to iron out, this specific issue has been resolved so I'll close this out.
