### ISSUE TITLE
Camera Exposure IPR Bug

### ISSUE THREAD

**Issue by AlexeyAdamitsky** [lunadigital/btoa#190]
Camera exposure isn't working in IPR.

![image](https://user-images.githubusercontent.com/64398828/184209832-f923c948-4615-42e4-93aa-f647ce9de02b.png)

Blender 3.2.2
BtoA Dev Build https://github.com/lunadigital/btoa/commit/66213cfccdd7e23143a86d4f7aa8a0e7884b7453

**Comment by osiriswrecks** [comment]
This is ready for testing on the `190_camera_exposure_ipr_bug` branch.

**Comment by AlexeyAdamitsky** [comment]
It's working now. Thank you for fixing this 👍
