### ISSUE TITLE
Physical Sky Node Control Issue

### ISSUE THREAD

**Issue by AlexeyAdamitsky** [lunadigital/btoa#192]
Physical Sky rotation node widget isn't working correctly. There are probably some axis rotation mismatches.

Here is how it's working in the Octane.

https://user-images.githubusercontent.com/64398828/184600947-ff712b37-725b-4579-acac-53eba035ff98.mp4

Here is what we have in the Arnold now.

https://user-images.githubusercontent.com/64398828/184601839-f1055f57-19c4-4536-a473-d84e51046cf6.mp4

I believe there are some XYZ mismatching. Probably need to shift rotation 90 or -90 degrees at one of the axis. Probably at X.

The shadow terminator should match the node's widget shadow terminator.
![image](https://user-images.githubusercontent.com/64398828/184601483-9cdcf9f0-221a-4dc4-9a7a-c4f6c97598a4.png)

Here is the scene file if you need to check the issues for yourself.

[2022-08-15 Physical Sky.zip](https://github.com/lunadigital/btoa/files/9336012/2022-08-15.Physical.Sky.zip)

Blender 3.2.2
BtoA Dev Build https://github.com/lunadigital/btoa/commit/66213cfccdd7e23143a86d4f7aa8a0e7884b7453

**Comment by osiriswrecks** [comment]
This is ready for testing! @AlexeyAdamitsky under the `192-physical-sky-node-control-issue` branch.

**Comment by AlexeyAdamitsky** [comment]
I tested it. Everything looks good! All parameters work as expected.
