### ISSUE TITLE
Refining Bump 2D & Bump 3D Nodes

### ISSUE THREAD

**Issue by AlexeyAdamitsky** [lunadigital/btoa#193]
Bump 2D and Bump 3D nodes needs some further refinement.

![image](https://user-images.githubusercontent.com/64398828/184869782-d85c9e5e-1eca-4dcd-b6d1-0699d1f9fc1a.png)
1. Bump Map input should be a float, not vector input in Bump 2D note.
2. Bump 3D node output is should be **vector** output.
![image](https://user-images.githubusercontent.com/64398828/184873746-828fc405-2a22-4ad0-b729-5d95b327159d.png)
3. The Bump Map value should be from 0 to 1. The default should be 0. Soft max should be 1.
![image](https://user-images.githubusercontent.com/64398828/184875095-ad507fec-9d73-4b65-b09f-eb34bebfd8ee.png)
4. Copy the Bump Height field design from Bump 2D node to Bump 3D node.
![blender_E4da9eeR9c](https://user-images.githubusercontent.com/64398828/184875780-0a5cf8f5-1910-4068-b4ab-56b13ce5b52b.gif)
5. **Discuss.** It may appear that Epsilon is at zero by default. Which is not true. If you click on the value you'll see that it's 0.001 by default. It might be not an issue in many cases but when you work at small sizes even this default value can change that texture quite drastically confusing the user. I recommend we make sure the value shows 3 numbers after the point.
![image](https://user-images.githubusercontent.com/64398828/184876826-9f72e989-0aa8-4c84-9c8c-91910e79819f.png)
6. **Optional.** I recommend we make the default size of the node at 160 pixels. It allows to show all the fields texts.

**Comment by AlexeyAdamitsky** [comment]
7. **Optional.** If it's not a big undertanking maybe we should also match other addons and also output XYZ floats (grayscale maps) for Bump2D / Bump3D nodes.
![image](https://user-images.githubusercontent.com/64398828/184913188-7aa86aa7-34fd-4363-a066-e3ebf1adce3b.png)

**Comment by AlexeyAdamitsky** [comment]
Made the mockup for the nodes final look.
![image](https://user-images.githubusercontent.com/64398828/185110508-24dd525a-6f28-424c-af98-27756fedb431.png)

**Comment by osiriswrecks** [comment]
@AlexeyAdamitsky All changes have been made! Ready to test.

**Comment by AlexeyAdamitsky** [comment]
Needs some more work.

**Bump2D**
![image](https://user-images.githubusercontent.com/64398828/185914749-de69d440-3017-4de0-85de-4754e4cc8c89.png)

1. It should be a float input. Default is 0. Soft minimum is 0. Can go into negative values. Soft maximum is 1. You can put a color (RGB) value in the float input but it'll only accept the the first channel and it's float data.
2. Should be all 3 channel available — X, Y and Z. Each can output float/grayscale map.
3. Make the default node width at 160px so all the texts are visible when the node is added.

**Comment by osiriswrecks** [comment]
Ahhh yep yep. I'll fix those up today.

**Comment by AlexeyAdamitsky** [comment]
Both Bump 2D and Bump 3D work good now. Don't see any issue nor crashes since the latest dev builds.

There is only the matter of QoL changes and UI/UX consistency.

1. We need to remove XYZ output nodes.
2. I don't see any practical value in exposing controls for the Bump Map input. I suggest we remove the controls. Leave only the input name, and make sure it's a **Float** input socket type.
3. Make sure the default Bump Height is 1 by default for Bump 3D.
4. I'm torn about this one. I, personally, believe we should have 0 to 1 slider for Bump Height for both nodes. Like Bump 3D node has. But I can imagine -1 to 1 can be somewhat useful for fast access to inverting the Bump Map. The problem is that the control is very bad near 0 range, and it's easy to jump to negative numbers. It's much easier to control in 0 to 1 range. I suggest we make sure both nodes use soft min/max 0 to 1 slider for high with possibility to manually go into negative range.
If there is strong case for the -1 to 1 range, I am okay with that too, but then we need to change it for Bump 3D node to foo consistency.
5. Set the default nodes with at 150px so all the labels fit.

![image](https://user-images.githubusercontent.com/64398828/219656319-707b22c3-706a-4511-9424-59542bca1b97.png)
