### ISSUE TITLE
Standard surface SSS defaults are wrong

### ISSUE THREAD

**Issue by osiriswrecks** [lunadigital/btoa#194]
Radius and scale should both be 1 by default, not 0.

**Comment by AlexeyAdamitsky** [comment]
Also the weight allows for negative values. I don't think it's correct. SSS Weight should be 0 by default. Hard min is 0 and hard max is 1.

**Comment by AlexeyAdamitsky** [comment]
We missed some other issues with the values.
![image](https://user-images.githubusercontent.com/64398828/185858085-03bcf542-4212-4e27-8c51-08d00ab4614d.png)

**SSS Scale**
Hard Min should be 0. Can't go into negatives. The default is 1 which is correct but soft max is should be 10.

**SSS Anisotropy**
The default is correct. In HtoA hard min is set to -0.99 and hard max 0.99. In C4DtoA it's -1 to 1. But to be honest I never used this parameter so I'm not sure which is one is the correct one.

**Comment by osiriswrecks** [comment]
For SSS Scale, we can clip min at 0 no problem. I think I'm going to leave the soft max where it is though, because you can't just go adjusting mins and maxes for each socket on the fly. You need to write a completely new custom socket if you want to customize it, so to keep that code from getting completely out of control I'm trying to stick to a handful of generalizations that work for most situations. Because soft maxes or mins don't break functionality or cause crashes if you get it "wrong", I tend to group them under a more general node, like `AiNodeSocketFloatPositive` in this case.

I'm working on cleaning up float sockets in general, because there are some redundancies and really poor naming choices in there right now.

SSS anisotropy is -1 to 1 (https://docs.arnoldrenderer.com/display/A5NodeRef/standard_surface#standard_surface-subsurface_anisotropy). I'm not sure why HtoA is clipping it, but we can change it in BtoA to match C4DtoA and the docs.
