### ISSUE TITLE
Node Request: Shading State Nodes

### ISSUE THREAD

**Issue by AlexeyAdamitsky** [lunadigital/btoa#196]
[Shading state nodes](https://docs.arnoldrenderer.com/display/A5AFHUG/Shading+State) are very needed for a variety or shading tasks. But it's needed badly to be able to create procedural materials. 

State shading nodes should go into a separate **State** category in the main shading menu.

![image](https://user-images.githubusercontent.com/64398828/185107717-009b6399-0590-416b-a9e3-2a454d4b9f0d.png)
**State Vector**
Ray Origin (Ro)
Ray Direction (Rd)
Shading Point in Object-Space (Po)
Shading Point in World-Space (P)
Surface Derivative WRT Screen X (dPdx)
Surface Derivative WRT Screen Y (dPdy)
Shading Normal (N)
Face-Forward Shading Normal (Nf)
Geometric Normal (Ng)
Face-Forward Geometric Normal (Ngf)
Smoothed Normal (No Bump) (Ns)
Surface Derivative WRT U (dPdu)
Surface Derivative WRT V (dPdv)
Ray Direction Derivative WRT Screen X (dDdx)
Ray Direction Derivative WRT Screen Y (dDdy)
Surface Normal Derivative WRT Screen X (dNdx)
Surface Normal Derivative WRT Screen Y (dNdy)

![image](https://user-images.githubusercontent.com/64398828/185107849-a994bac0-dfbd-4b3f-96f0-6221555855bf.png)
**State Float**
Screen X (sx)
Screen Y (sy)
Subpixel X (px)
Subpixel Y (py)
Shutter Time (time)
Ray Length (RI)
Barycentric U (bu)
Barycentric V (bv)
Surface U (u)
Surface V (v)
Shaded or Avg. Displaced Area (area)
U Derivative wrt Screen X (dudx)
U Derivative wrt Screen Y (dudy)
V Derivative wrt Screen X (dvdx)
V Derivative wrt Screen Y (dvdy)
Shutter Start (shutter_start)
Shutter End (shutter_end)

![image](https://user-images.githubusercontent.com/64398828/185176844-a27dacb0-d453-43f0-b3a0-1b0f1cad6133.png)
**State Integer**
Raster X (x)
Raster Y (y)
Subpixel Sample Index (si)
Ray Type (Rt)
Transparency Index (transp_index)
Thread ID (tid)
Total Bounces (bounces)
Diffuse Bounces (bounces_diffuse)
Specular Bounces (bounces_specular)
Reflection Bounces (bounces_reflect)
Transmission Bounces (bounces_transmit)
Volume Bounces (bounces_volume)
Force Hemispherical Lighting (fhemi)
Primitive ID (fi)
Number of Active Lights (nlights)
Inclusive Traceset (inclusive_traceset)
Skip Shadow Rays (skip_shadow)
Shading Context (sc)

**Comment by osiriswrecks** [comment]
Added with 432421d, cbae797, and 9c569aa
