### ISSUE TITLE
Node Request: Curvature

### ISSUE THREAD

**Issue by AlexeyAdamitsky** [lunadigital/btoa#197]
The [Curvature](https://docs.arnoldrenderer.com/display/A5AFHUG/Curvature) is another core procedural node we need.

![image](https://user-images.githubusercontent.com/64398828/185556202-03a24b6b-35e9-46a9-897e-748f9b4c08ec.png)

**Output**
Convex (Default), Concave, Both

**Samples**
Integer. 3 is the default. 1 is hard minimum. 10 is soft maximum.

**Radius**
Float. 0.1 is the default. 0 is hard minimum. 1 is soft maximum.

**Spread**
Float. 1 is the default. 0 is hard minimum. 1 is hard maximum.

**Threshold**
Float. 0 is the default. 0 is hard minimum. 1 is hard maximum.

**Bias**
Float. 0.5 is the default. 0 is hard minimum. 1 is hard maximum.

**Multiply**
Float. 1 is the default. 0 is soft minimum. 10 is soft maximum.

**Trace Sets** & **Inclusive**
These two settings are working together. By the default I think we shouldn't worry much about it. But trace sets should be specified in the geometry nodes visibility options if you want to use it where you define trace sets naming first. I'm not sure yet how well this can be handled for now. We can maybe leave these two options out for now so users can't mess up this node.

**Comment by osiriswrecks** [comment]
@AlexeyAdamitsky Beautiful. Something to keep in mind when mocking up nodes...there are two parts to a node in Blender: node variables, and sockets. Variables—or class annotations—are drawn above the sockets, always. See this screenshot as an example:

![image](https://user-images.githubusercontent.com/24221107/185278911-f169eb4a-7809-4dc5-8e7b-3cc20f650217.png)

There's no control over this, so even though your mockup looks great, it's not possible to format this way in the Blender UI. We'd have to put the trace set/inclusive/self-only above the sockets.

**Comment by osiriswrecks** [comment]
This is ready to test on `dev`!

![image](https://user-images.githubusercontent.com/24221107/185284569-ab1c0c1d-aa5f-468e-aa70-eedfceb27018.png)

**Comment by AlexeyAdamitsky** [comment]
Just to note that we're missing R, G, B outputs. It's pretty important to have these output. Especially if you want to use Both curvature output option. Since when Both is used the node will split the concave and convex for red and green channels.
![Curvature3-3](https://user-images.githubusercontent.com/64398828/185569224-766c44de-e61b-4686-84c5-85d068cbc9e4.jpg)

It's more convenient to access each separate channel from the node to get the value from each output type.

I also recommend we remove **:** after the **Output**. Changing “Output:” → “Output”.
