### ISSUE TITLE
Correct Facing Ratio Node Output to Float

### ISSUE THREAD

**Issue by AlexeyAdamitsky** [lunadigital/btoa#198]
Currently the output is set to shared RGB.
![image](https://user-images.githubusercontent.com/64398828/185553159-ceebb7fb-154d-4b98-8074-3c9493ac4dcc.png)

The proper output would be Float.
![image](https://user-images.githubusercontent.com/64398828/185553423-2dbb8928-66c8-4292-a4f8-7b77881b5463.png)

**Comment by osiriswrecks** [comment]
@AlexeyAdamitsky This is ready to test!

**Comment by AlexeyAdamitsky** [comment]
It's correct now. Thanks!
