### ISSUE TITLE
Node Request: RGB to Float, RGBA to Float

### ISSUE THREAD

**Issue by AlexeyAdamitsky** [lunadigital/btoa#205]
**RGB to Float**
![image](https://user-images.githubusercontent.com/64398828/186351977-8c3a9e9d-36bb-4057-abe2-ded06933ef82.png)

**Output**
Float data.

**Input**
Color data. The default is 0.0.0 or black.

**Mode**
- Min
- Max
- Average (Default)
- Sum
- Luminance
- R
- G
- B

**RGBA to Float**
![image](https://user-images.githubusercontent.com/64398828/186352010-62a369e6-6e54-4781-a2fe-ee4da2ac235b.png)

The only difference between two nodes is that it can accept image data containing alpha and thus has a mode (**A**) to convert this channel to float.

**Comment by osiriswrecks** [comment]
@AlexeyAdamitsky If I'm reading the docs right, we could probably replace our new Separate RGBA node with these. https://docs.arnoldrenderer.com/display/A5NodeRef/rgb_to_float

When `RGBA` is selected in the dropdown (as one "RGBA" option), we can hide the standard "float" output and show the 4 individual R, G, B, and A outputs instead. I'll code this up tonight for you to see.

**Comment by osiriswrecks** [comment]
@AlexeyAdamitsky Because they're pretty much redundant, except for the alpha channel, let's start with RGBA to float only. It appears MtoA has done this - there's an RGBA to float node, but no RGB to float node.
