### ISSUE TITLE
Mix Shader is Broken Now

### ISSUE THREAD

**Issue by AlexeyAdamitsky** [lunadigital/btoa#214]
Trying to use Mix Shader node with no nodes connected to Shader inputs either breaks IPR with the error below or crashes Blender entirely.
![image](https://user-images.githubusercontent.com/64398828/187509017-64131cea-669b-4783-8fdd-1a4d2a641156.png)

This setup breaks IPR and crashes Blender.
![image](https://user-images.githubusercontent.com/64398828/187509216-f3099263-1096-4462-8cf1-68d3774619f5.png)

When all the nodes are connected prior to IPR activation it works ok.
![image](https://user-images.githubusercontent.com/64398828/187509385-03b5d343-e6cc-42ff-a06e-d7d859dc330f.png)

Blender 3.2.2
Arnold SDK 7.1.2.2
BtoA Dev Build https://github.com/lunadigital/btoa/commit/9757d957ea8ec4406908a14cd7b0a2637fbd36a7

**Comment by osiriswrecks** [comment]
My guess is it's always done this, we just haven't noticed until now. There should be some kind of sanity check we can do to avoid it trying to export an unplugged socket.

**Comment by AlexeyAdamitsky** [comment]
It works really well now. No errors when shader inputs are empty. Thanks!
