### ISSUE TITLE
Mix Shader Node Design Polish

### ISSUE THREAD

**Issue by AlexeyAdamitsky** [lunadigital/btoa#215]
![image](https://user-images.githubusercontent.com/64398828/187703779-8332f585-339b-453b-8326-7aaa7113038d.png)

1. Change name from “Closure” to “Shader”.
2. Remove "Mode:" label to allow the drop down menu to fill the width of the node.
This is the the minimum goal for the node clean up.

I also have a design change for the node to make it more user friendly. I don't know if it's too difficult to implement or not.

https://user-images.githubusercontent.com/64398828/187704185-6ef26a95-156c-4da4-b958-561be73964bc.mp4

3. Basically we want the node to change when we're switching mixing modes. Blend is the default and it doesn't have the “Add Transparency option”. It's pretty much a legacy feature. Even when switching to Add mixing mode it is not recommended to use this. Still it's there for some users. But when you're switching to Add mixing mode there should be no mix factor controls since it can't be controlled for this mode.

Let me know if this can't be implemented. But I tried to apply good UI/UX practices here to allow for maximum transparency for the user which is options are available for him with different modes chosen.

Also you pretty much all the time better use the default Blend mode 😎 which makes the node a bit more compact.

**Comment by AlexeyAdamitsky** [comment]
Really good work! One last polish though.

Can we make sure the connection to the hidden setting is cut off when the modes are changing? Here is an example from Cycles.

https://user-images.githubusercontent.com/64398828/187846774-dc8b4271-1636-45cf-aaa8-3c6037432586.mp4

Currently with out node we have this behavior which will be misleading if we don't cut the connection when switching modes.

https://user-images.githubusercontent.com/64398828/187847048-6006cbb7-124c-41ef-9cca-ac2788410330.mp4

**Comment by osiriswrecks** [comment]
Let me look into this further. I'm sure we can find a way to make it work.

**Comment by osiriswrecks** [comment]
Now that we're talking about re-organizing sockets in #228 should we revisit this mockup?
