### ISSUE TITLE
OCIO Issue with Blender 3.3 LTS

### ISSUE THREAD

**Issue by AlexeyAdamitsky** [lunadigital/btoa#218]
Arnold seems to have some issues with OCIO setup in Blender 3.3 LTS.

![image](https://user-images.githubusercontent.com/64398828/192281519-fa51aefd-c6e3-4bdb-be13-0d5db3f205bb.png)

**Comment by madcap66** [comment]
Same here using 3.3 LTS. 

Got btoa to work by adding a folder "3.2" to the root of the blender install and copied "datafile/colormanagement" into the 3.2 folder...seemed to work for now. Renders at least until a fix is issued.
