### ISSUE TITLE
BtoA not working for Blender 3.3.1 LTS

### ISSUE THREAD

**Issue by Hidetoshi6721** [lunadigital/btoa#220]
![image](https://user-images.githubusercontent.com/85873175/201462794-5767ac6f-00e5-4248-94e3-9f80cc47f6ef.png)

I get this error message when trying to enable the addon.

**Comment by osiriswrecks** [comment]
Hi @Hidetoshi6721 - sorry for the late reply. This is a known issue and we will address it once we work out some installation-related tasks. Thanks for submitting a ticket!
