### ISSUE TITLE
Add Nodes Menu is Populated with Foreign Data

### ISSUE THREAD

**Issue by AlexeyAdamitsky** [lunadigital/btoa#223]
Search menu is populated with strange entries when searching for nodes in Add Nodes menu.

https://user-images.githubusercontent.com/64398828/219020533-e8ec1b54-fc8d-4b72-83bd-b2783815db22.mp4

Blender 3.4.1
BtoA Dev 27de524

**Comment by osiriswrecks** [comment]
This appears to no longer be an issue in Blender 4.0. Closing for now.
