### ISSUE TITLE
Shader Editor Snap Settings Are Ignored

### ISSUE THREAD

**Issue by AlexeyAdamitsky** [lunadigital/btoa#224]
Changing snapping settings in the shading editor doesn't do anything. I believe this might be broken because some time ago Blender allowed the snapping setting to be local to the editor. Before, this feature was global. So you might need to revisit this code to make sure it's working properly.

https://user-images.githubusercontent.com/64398828/219608232-9110ec23-c125-44c7-ae05-629f03290df9.mp4

You can still snap using modifier hotkey, but the interface settings don't work.

Blender 3.4.1
BtoA Dev https://github.com/lunadigital/btoa/commit/27de524d5856fb3ba3b9566e633f97af6d328901

**Comment by osiriswrecks** [comment]
As far as I know we don't really have control over this. I can file a bug report with Blender, though, and we can see where it goes. I'll keep this open for now.

**Comment by osiriswrecks** [comment]
This appears to be a blender bug. Can't fix from our end.
