### ISSUE TITLE
Interrupting Render Process Is Crashing Blender

### ISSUE THREAD

**Issue by AlexeyAdamitsky** [lunadigital/btoa#225]
Initialize the render process with F12. Before the render is finished, press ESC key and Blender will crash with BtoA.

Attaching logs file:
[arnold-2023-02-17-17-41-42.log](https://github.com/lunadigital/btoa/files/10767902/arnold-2023-02-17-17-41-42.log)

Blender 3.4.1
BtoA Dev https://github.com/lunadigital/btoa/commit/27de524d5856fb3ba3b9566e633f97af6d328901

**Comment by osiriswrecks** [comment]
I've seen this from time to time myself but haven't tracked down what's causing it. It doesn't always reliably crash for me. I can do a deeper dive soon.
