### ISSUE TITLE
Area light doesn't change subtype during IPR

### ISSUE THREAD

**Issue by osiriswrecks** [lunadigital/btoa#227]
Changing between quad/disk/cylinder doesn't react as expected.

**Comment by AlexeyAdamitsky** [comment]
Area Light shapes aren't switching correctly either.

https://user-images.githubusercontent.com/64398828/220281824-396d14ea-d82f-43ab-b385-fdcdd3d5b0f4.mp4

**Comment by AlexeyAdamitsky** [comment]
Light types aren't switching in IRP correctly either.

https://user-images.githubusercontent.com/64398828/220283146-123716b2-e820-4af9-9d54-393fc21061e7.mp4
