### ISSUE TITLE
Sss scale not respecting Model scale

### ISSUE THREAD

**Issue by Noahmuiruri** [lunadigital/btoa#230]
Sss scale does not respect the model scale..
tested on blender 3.5
here is the test file:
![blender 3 5 arnold sss](https://user-images.githubusercontent.com/29056816/234361818-6a5cadef-ec23-4214-8830-e09893e6e583.png)

blender 3.5
Maya 2022:
[scale_measure.zip](htt
![Maya 2022 arnold sss](https://user-images.githubusercontent.com/29056816/234361868-c134afe5-d069-48e8-a7fa-08d1307be07e.png)
ps://github.com/lunadigital/btoa/files/11312706/scale_measure.zip)

**Comment by osiriswrecks** [comment]
It took a bit of back and forth between Blender and Maya, but I think I understand what's happening. In Maya, SSS Scale seems to be based on centimeters, regardless of what the scene units are set to. In Blender, it's based on meters. So to get the materials to match, a SSS scale of "1" in Maya is the same as "0.01" in Blender. I'm not 100% sure how I will implement this fix yet but I believe this will solve this issue.
