### ISSUE TITLE
Can't reinstall the addon

### ISSUE THREAD

**Issue by Behboudi1989** [lunadigital/btoa#234]
I installed the addon once and didn't import the log file and I accidentally removed the addon, and after installing the addon again to import the log file I'm getting this error
![Screenshot (89)](https://github.com/lunadigital/btoa/assets/116750278/191c25da-9f66-452a-8091-6901d57b8da4)

**Comment by osiriswrecks** [comment]
@Behboudi1989 To be safe, you should uninstall the add-on, close Blender completely, then re-open and install the latest version. This isn't necessarily an BtoA thing, but will often happen with Blender add-ons in general.

Make sure you're using the latest `dev` branch - it's been a while since the latest release and I'm still putting final touches on our 0.5.0 release. Feel free to join our Discord if you have any questions!

**Comment by Behboudi1989** [comment]
> @Behboudi1989 To be safe, you should uninstall the add-on, close Blender completely, then re-open and install the latest version. This isn't necessarily an BtoA thing, but will often happen with Blender add-ons in general.
> 
> Make sure you're using the latest `dev` branch - it's been a while since the latest release and I'm still putting final touches on our 0.5.0 release. Feel free to join our Discord if you have any questions!

Reopening blender fixed it, but now my vieport render doesn't work, everything is transparent

**Comment by osiriswrecks** [comment]
We provide one-on-one support through our Discord server. Join us there and I'd be happy to take a look with you. Once you're in, be sure to share your Arnold logs right after a render so we can figure out what's going on (you can tell BtoA to write out to a log file in the add-on preferences, or you can open the console window and look there). See you on the Discord!

**Comment by Behboudi1989** [comment]
> We provide one-on-one support through our Discord server. Join us there and I'd be happy to take a look with you. Once you're in, be sure to share your Arnold logs right after a render so we can figure out what's going on (you can tell BtoA to write out to a log file in the add-on preferences, or you can open the console window and look there). See you on the Discord!

Sure, thanks
