### ISSUE TITLE
Add support for downloading directly from Autodesk

### ISSUE THREAD

**Issue by NicSJ** [lunadigital/btoa#235]
> As of January 15, 2024, Arnold plugins/downloads will only be available via your Autodesk Account and the 'Arnold Plug-ins & Additional Software' box in Autodesk Account, which redirects to arnoldrenderer.com, will be removed.

The current auto download and install system will break after they implement this.

For more information see [https://www.autodesk.com/support/technical/article/caas/tsarticles/ts/eorabccFiriUrZ7ZHvUVg.html](url)

**Comment by osiriswrecks** [comment]
I'm aware of this change and have an open ticket with Autodesk to see what the next best move is. I don't know if downloading directly from Autodesk is even possible at the moment, but if I had to guess they probably want it walled off by user auth. I will leave this issue open and let you know how it goes over the next week or two as I find out more.

**Comment by NicSJ** [comment]
Thanks for the quick reply. I know most of their software is available as direct downloads, I'm just not sure what the best source for them is, or how they are generated. See [https://forums.autodesk.com/t5/installation-licensing/2022-products-direct-download-links/td-p/10178655](url) for examples. The most common URLs seem to start with "https://dds.autodesk.com" or "https://up1.autodesk.com".

**Comment by osiriswrecks** [comment]
OH I've never noticed that. Thanks for the links, I'll take a look at it this week while I wait for AD to respond.

**Comment by osiriswrecks** [comment]
I've been chatting with AD for the past day or so about options, and they're not really giving us much to work with. They're recommending we point users to Autodesk.com so they can download the SDK themselves, or pay to join the Developer Network and "work more collaboratively with Autodesk". So it sounds like this move will absolutely brick the way we're installing the add-on right now.

The goal with the new installation was to avoid users having to go through so many steps to set up BtoA, but it looks like AD wants to force our hand. I want to go back and forth a little more over before making a next step but we'll have to have a plan this week to avoid UX issues.

**Comment by osiriswrecks** [comment]
We joined the Autodesk Developer Network in an effort to get more options from Autodesk on how to move forward long-term on this. For now, we're hosting the compatible SDKs on our own server with the understanding that it's a stop-gap measure until I can talk more thoroughly with Autodesk. Closing this issue for now.
