### ISSUE TITLE
Unable to render when "Render Region" is turned on.

### ISSUE THREAD

**Issue by Arrovmaker002** [lunadigital/btoa#237]
I tend to have this on by default by habit and it turns out it messes with Arnold recognizing the render format. Rendering starts and is active but none of the image is calculated and Arnold throws this error on repeat:

> ValueError: ARNOLD.begin_result(): error with argument 1, "x" -  Function.x value not in 'int' range ((-2147483647 - 1), 2147483647)
Exception ignored on calling ctypes callback function: <function ArnoldRenderEngine.render.<locals>.update_render_result at 0x00000298B73D4160>
Traceback (most recent call last):
  File "E:\software\Blender\Blender Arnold\4.0\scripts\addons\btoa-dev\engine.py", line 170, in update_render_result
    result = engine.begin_result(x, y, rdata.width, rdata.height, layer=cache.view_lay
    
This error is a snippet from the blender console whilst rendering:
[Blender Arnold Console Log.txt](https://github.com/lunadigital/btoa/files/14003441/Blender.Arnold.Console.Log.txt)
er.name)

**Comment by osiriswrecks** [comment]
It appears to only error and crash the render if the render region encompasses the _whole_ image (ie, equals the resolution of the actual render). Once you change it to be a smaller part of the image it works as expected.

**Comment by Arrovmaker002** [comment]
can confirm
