### ISSUE TITLE
Camera Focal Lenght Mismatch

### ISSUE THREAD

**Issue by AlexeyAdamitsky** [lunadigital/btoa#25]
Blender 2.91.2
BtoA Dev Branch be798c0
Arnold SDK 6.1.0
Windows 10 2004

What you see in camera viewport is not what you get in render in Arnold.

![image](https://user-images.githubusercontent.com/64398828/108132697-5c566980-70c4-11eb-8ce3-592f22698ca3.png)

**Comment by osiriswrecks** [comment]
@AlexeyAdamitsky Can you upload this file so I can test some more?

**Comment by osiriswrecks** [comment]
I have a sneaking suspicion it's actually related to the Blender camera's sensor fit setting, not the focal length directly. It seems to render as expected with "Auto" selected, but might need to be adjusted if another value is set.

**Comment by osiriswrecks** [comment]
After some research I'm positive it's sensor fit related, because your render here is a portrait-style render. We would just have to recalculate the FOV for portrait-style renders (where the height is larger than the width) because Arnold assumes the FOV to define the horizontal FOV.

**Comment by osiriswrecks** [comment]
@AlexeyAdamitsky When you get a chance, try a build with the commit referenced above and see if that fixes it for you.

**Comment by AlexeyAdamitsky** [comment]
Yes, everything works now as expected here.
