### ISSUE TITLE
Render Visibility Controls Don't Work for Light Objects

### ISSUE THREAD

**Issue by AlexeyAdamitsky** [lunadigital/btoa#29]
Blender 2.91.2
BtoA Master Branch e2820a1
Arnold SDK 6.1.0
Windows 10 2004

Turning off Render Visibility for lights doesn't work.
![image](https://user-images.githubusercontent.com/64398828/108197092-f3eea300-712a-11eb-8938-ea67efc59b2c.png)

**Comment by osiriswrecks** [comment]
Tangentially related to issue #27

**Comment by AlexeyAdamitsky** [comment]
Works now as expected. Thanks!
