### ISSUE TITLE
Point Light: Radius Control is Broken

### ISSUE THREAD

**Issue by AlexeyAdamitsky** [lunadigital/btoa#30]
Blender 2.91.2
BtoA Master Branch e2820a1
Arnold SDK 6.1.0
Windows 10 2004

![image](https://user-images.githubusercontent.com/64398828/108197331-4a5be180-712b-11eb-88f6-643dec7e8181.png)

It has some issues:
1. It needs to calculate radius in scene units.
2. Gizmo doesn't work:
Here is the expected behavior.
![EhWMduqCGb](https://user-images.githubusercontent.com/64398828/108198720-09fd6300-712d-11eb-8a01-0b0a7ff3bbb2.gif)
Here is the behavior in Arnold.
![vQNPRXdPfc](https://user-images.githubusercontent.com/64398828/108198704-036eeb80-712d-11eb-8e8e-a3a7c7816de0.gif)

**Comment by AlexeyAdamitsky** [comment]
I've just re-read point light specifications. It fits well into Blender's convention of Point Light as well.

The name of this light is 'point' for historical reasons in Arnold. Thought it really is an emissive sphere, **unless radius is set to zero**, in which case it becomes **a true point light** of no physical size.

I don't know if it's possible but I suggest this solution. Add point light with **0** Radius. It's already like this by default but also make sure that this is reflected in gizmo controls if possible. It will be an idea scenario here.

**Comment by osiriswrecks** [comment]
It's actually a lot simpler than that, I think. Changing the radius value doesn't affect the UI but it does affect the render - that's because I'm pretty sure it's a custom property at the moment. If we swap it out for Blender's default "size" property, it should work as expected.

**Comment by AlexeyAdamitsky** [comment]
Cool. Great to hear there might be a simpler solution.
