### ISSUE TITLE
Lights: Implement Camera Visibility Light Attribute

### ISSUE THREAD

**Issue by AlexeyAdamitsky** [lunadigital/btoa#31]
Blender 2.91.2
BtoA Master Branch e2820a1
Arnold SDK 6.1.0
Windows 10 2004

I would consider this to be a priority attribute for lights to implement.
![firefox_B0fWeofw9U](https://user-images.githubusercontent.com/64398828/108221725-2909ee00-7149-11eb-8a76-02ef6416e987.png)

**Comment by AlexeyAdamitsky** [comment]
Related to #32 task.

**Comment by osiriswrecks** [comment]
Closing this issue in favor of #32
