### ISSUE TITLE
Lights: Implement Visibility Light Attributes

### ISSUE THREAD

**Issue by AlexeyAdamitsky** [lunadigital/btoa#32]
Blender 2.91.2
BtoA Master Branch e2820a1
Arnold SDK 6.1.0
Windows 10 2004

I don't consider these a priority. Except the Camera attribute. But eventually we'll need all of them.
![image](https://user-images.githubusercontent.com/64398828/108221108-7cc80780-7148-11eb-8524-ef771fad4fba.png)

**Comment by AlexeyAdamitsky** [comment]
Related to #31 task.

**Comment by AlexeyAdamitsky** [comment]
Thanks for adding this. It helps to test and troubleshoot lights much easier now.

I did some testing and everything seem to work as expected. The **Transmission Visibility** property (**1**) is missing though and it's off by default making it difficult to test glass materials. It would be great if we had the complete list here.

![image](https://user-images.githubusercontent.com/64398828/108334433-fad8ec80-71e2-11eb-96f6-70ff98b1390b.png)

**Comment by osiriswrecks** [comment]
@AlexeyAdamitsky Go ahead and test the transmission visibility now!

**Comment by AlexeyAdamitsky** [comment]
The list is complete and all seems to work as expected. I didn't do extensive testing here to look for bugs but couldn't spot anything broken with initial general testing. Good job!
