### ISSUE TITLE
Quad Light: Texture Mapping Issue

### ISSUE THREAD

**Issue by AlexeyAdamitsky** [lunadigital/btoa#34]
Blender 2.91.2
BtoA Master Branch e2820a1
Arnold SDK 6.1.0
Windows 10 2004

1. You can see how light is spreading from in a gradient from one side. It should be even gradient in all directions from the center if I'm not mistaken.
![image](https://user-images.githubusercontent.com/64398828/108233177-91aa9800-7154-11eb-8da4-17c1be7195c8.png)
I suspect there is a texture mapping issue here.

2. It seemingly affects the **Roundness** parameter. This area is pointier as if it should be the center from which the roundness affects the texture.
![image](https://user-images.githubusercontent.com/64398828/108233506-e817d680-7154-11eb-97e9-4acefcf5f247.png)

3. And it definitely affect the **Soft Edge** parameter. You can notice how it get softer from it's probable center.
![image](https://user-images.githubusercontent.com/64398828/108233897-45138c80-7155-11eb-952d-dbc1976f8da7.png)
![image](https://user-images.githubusercontent.com/64398828/108235306-c0297280-7156-11eb-9ddb-f1f12bc7685e.png)

It probably affects other lights as well. Haven't checked yet.

**Comment by osiriswrecks** [comment]
@AlexeyAdamitsky Can you provide a test file for this?

**Comment by AlexeyAdamitsky** [comment]
I was testing this again and I can't reproduce the bug. It behaves as expected. I'm not sure what happened but you probably fixed it somehow since the time I reported it.

I'll close the issue now. If it comes back I'll open a new issue.
