### ISSUE TITLE
Cylinder Light: Size Controls Are Broken

### ISSUE THREAD

**Issue by AlexeyAdamitsky** [lunadigital/btoa#41]
Blender 2.91.2
BtoA Dev Branch 84331f7
Arnold SDK 6.1.0
Windows 10 2004

Cycles has two controls for rectangle light.
![b0PaUlP0e8](https://user-images.githubusercontent.com/64398828/108339104-11ce0d80-71e8-11eb-8c16-7d3e9dc7c99b.gif)
I assume we're using the same model for Cylinder Light.
Currently we have only **Size** value to adjust. It corresponds to **X** value for the gizmo as far as I understand.
![image](https://user-images.githubusercontent.com/64398828/108339443-7d17df80-71e8-11eb-9179-e1e999d462c8.png)
Also what it really controls is the **Radius** of the Cylinder light.
We need to add another property which corresponds to **Y** value for the gizmo to control the **Height** parameter of the light.
![PotPlayerMini64_5YsKLNbwlp](https://user-images.githubusercontent.com/64398828/108340320-7f2e6e00-71e9-11eb-89c0-71f1c0545056.png)

While we don't have true cylindrical gizmo to have properly show the light form in the viewport this solution is close enough.

P.S. I checked on the somewhat working Radius (Size) property of the light and it suffer from the same issue that the rest of lights with new controls. The size of the light is twice as large in the viewport.

**Comment by osiriswrecks** [comment]
This is addressed in commits 4842fdd and d07252a.
