### ISSUE TITLE
Spot Light: Broken Controls and Missing Features

### ISSUE THREAD

**Issue by AlexeyAdamitsky** [lunadigital/btoa#43]
Blender 2.91.2
BtoA Dev Branch 7ff4042
Arnold SDK 6.1.0
Windows 10 2004

**Note:** Reporting this based on an older branch since the light is broken in the latest build and I can't test it.

Radius control (**3**) is not working in this build. I think it was implemented in the latest build but unfortunately something else broke and it wasn't possible for me to test. Although, I suspect it might also suffer size issues I described for other lights. Needs testing though to make sure.
![image](https://user-images.githubusercontent.com/64398828/108353189-e7388080-71f8-11eb-8989-7a452b589c34.png)

We're missing **Cone Angle** and **Penumbra Angle** controls.
![image](https://user-images.githubusercontent.com/64398828/108352190-92483a80-71f7-11eb-9c47-381a1e091dae.png)
Blender already have these controls for the light and Size (**Cone Angle**) is there to control the gizmo and Blend (**Penumbra Angle**).
I would also think about including **Show Cone** (2) control. I suspect  it just affects viewport just for visual help and shouldn't break anything in Arnold.
![image](https://user-images.githubusercontent.com/64398828/108352641-329e5f00-71f8-11eb-91c2-2303b651d47f.png)

**Drop Off** parameter is missing to control the intensity of the light compared to the edges.
![image](https://user-images.githubusercontent.com/64398828/108354158-23201580-71fa-11eb-860a-9e97b1ca59d8.png)

I also believe **Lens Radius** needs to be in scene units to make sense of this parameter and how it works. Otherwise it'll be hard to predictably control it.

![image](https://user-images.githubusercontent.com/64398828/108355326-bad23380-71fb-11eb-88da-1e885c662121.png)

**Comment by osiriswrecks** [comment]
@AlexeyAdamitsky I just tested the spot light radius on the latest build and it works fine for me. It might have broken when area lights caused some issues earlier today but it's good to go now. I'll look at implementing these other missing features.

**Comment by osiriswrecks** [comment]
Everything has been addressed except the drop off value. I can't find anything in the documentation about it - it might be deprecated, or renamed. We can table it for now and return later once we figure out where it went.

**Comment by AlexeyAdamitsky** [comment]
> Everything has been addressed except the drop off value. I can't find anything in the documentation about it - it might be deprecated, or renamed. We can table it for now and return later once we figure out where it went.

Yes, it might be. It's in Cinema4D but it's not in Maya. I don't think this parameter very important. It has very subtle effect on the light. I don't think it's important at the moment.

I checked everything else and it seems to work as expected. Thank you.
