### ISSUE TITLE
Render Region Doesn't Work

### ISSUE THREAD

**Issue by AlexeyAdamitsky** [lunadigital/btoa#56]
Blender 2.91.2
BtoA Alpha Branch f69a6d0
Arnold SDK 6.1.0
Windows 10 2004

Currently using Render Region doesn't work. You can activate render region in 3D viewport (**1**). Go to View → View Regions → Render Region...

As far as I can see it positions correctly relative to 3D veiwport (**2**) but the rendered image doesn't match and also produces artifacts on edges. 

![image](https://user-images.githubusercontent.com/64398828/108625465-2ca8b800-745c-11eb-8282-364137006223.png)

Also if you try to re-render render region Blender will crash. How to reproduce. Create a new scene or open the attached scene. Activate render region. Render. Now when it is finished render again. Blender will crash on second try.

It would be nice if we could fix it rather sooner than later. We don't have IPR yet it's so it's helpful to render regions for faster iterations and testing various aspects of BtoA addon.

Test scene:
[Arnold_Test_Scene6.zip](https://github.com/lunadigital/btoa/files/6017712/Arnold_Test_Scene6.zip)

**Comment by Noahmuiruri** [comment]
Also Border options show a mirrored edge when using render region
