### ISSUE TITLE
A few lines of errors code for installing 

### ISSUE THREAD

**Issue by phillecour-18** [lunadigital/btoa#58]
![Screen Shot 2021-02-21 at 11 36 37 AM](https://user-images.githubusercontent.com/79414360/108631839-f2c6ba00-7439-11eb-868e-1bbade48e13e.png)
![Screen Shot 2021-02-21 at 11 37 09 AM](https://user-images.githubusercontent.com/79414360/108631843-f4907d80-7439-11eb-8ac0-3e0978980d42.png)
![Screen Shot 2021-02-21 at 11 37 17 AM](https://user-images.githubusercontent.com/79414360/108631844-f5291400-7439-11eb-8235-d4a236c0226a.png)

If anyone can explain ?

**Comment by Noahmuiruri** [comment]
remove the addon completely:
Download the Arnold sdk from their website
set environment variable as per the instructions here https://github.com/lunadigital/btoa/wiki
you might need to restart your machine after setting the variable
install the add-on and reinitialize blender
hope it helps

**Comment by osiriswrecks** [comment]
@Noahmuiruri is right - at the very least you need to have an `LD_LIBRARY_PATH` environment variable set to include the path to Arnold's `bin` directory. You can optionally set an ARNOLD_ROOT environment variable, but if you don't it will let you select the path to Arnold's root directory in the add-on preferences.

**Comment by phillecour-18** [comment]
When this addons will be really user friendly let me know...

For now it's not and nothing work

Le dim. 21 févr. 2021, à 13 h 27, Aaron Powell <notifications@github.com> a
écrit :

**Comment by osiriswrecks** [comment]
@phillecour-18 We recently made some updates that might help you get up and running here. You no longer have to set `ARNOLD_ROOT` or `LD_LIBRARY_PATH` by hand. Check it out on the latest development branch.

https://github.com/lunadigital/btoa/tree/alpha-rc2

**Comment by phillecour-18** [comment]
Yes... for sure.

I keep you in touch!


Le mer. 24 févr. 2021, à 12 h 28, Aaron Powell <notifications@github.com> a
écrit :

**Comment by phillecour-18** [comment]
Now it work ...

Good job team

Good day

**Comment by phillecour-18** [comment]
Any document, i can read ?

**Comment by osiriswrecks** [comment]
We only have documentation about installation at the moment. We're planning out more documentation for both the project wiki and YouTube, but development is happening fast so it would become out-of-date relatively quickly.

Your best bet is to join in on the conversation either on BlenderArtists (https://blenderartists.org/t/arnold-for-blender-0-1-0-alpha-release/1284309) or on the Discord server (https://discord.gg/MqZpKFtsNT).
