### ISSUE TITLE
Cylinder Light: Gizmo Needs Adjustment

### ISSUE THREAD

**Issue by AlexeyAdamitsky** [lunadigital/btoa#60]
Blender 2.91.2
BtoA RC2 Branch 35b580e
Arnold SDK 6.1.0
Windows 10 2004

The new gizmo (the gray outline) for Cylinder Light needs just a bit of size adjustment to match active gizmo outline.
![Nq61kBocp3](https://user-images.githubusercontent.com/64398828/108748009-26473880-754f-11eb-8be6-0eadfdf2b970.gif)

**Comment by osiriswrecks** [comment]
Interestinggg. I'll take a look.

**Comment by osiriswrecks** [comment]
@AlexeyAdamitsky It's bizarre that for you it looks smaller than the light size.. For me, it looks bigger!
