### ISSUE TITLE
Arnold Nodes Invades Cycles Add Shader Menu

### ISSUE THREAD

**Issue by AlexeyAdamitsky** [lunadigital/btoa#62]
Blender 2.91.2
BtoA RC2 Branch 35b580e
Arnold SDK 6.1.0
Windows 10 2004

All Arnold nodes appear to be available in Cycles node editor.
![KVwGqOOfHj](https://user-images.githubusercontent.com/64398828/108764981-4cc39e80-7564-11eb-8046-e0b863f4bf8a.gif)

**Comment by osiriswrecks** [comment]
Noah mentioned this over the weekend. I'll see what I can do to remove it.

**Comment by osiriswrecks** [comment]
This should be fixed - please confirm when you get a chance. @AlexeyAdamitsky

**Comment by AlexeyAdamitsky** [comment]
The issue seems to be resolved now. Thank you.
