### ISSUE TITLE
Transmission Depth socket/ Parameter missing in Standard surface shader

### ISSUE THREAD

**Issue by Noahmuiruri** [lunadigital/btoa#63]
Depth is an important factor when rendering glass in Arnold,for now the parameter is missing

**Comment by Noahmuiruri** [comment]
Also Exit Background checkbox is missing

**Comment by osiriswrecks** [comment]
@Noahmuiruri There is a transmission depth setting in the main render panel, under Ray Depth. Is this what you mean?

![Screenshot from 2021-02-23 13-38-50](https://user-images.githubusercontent.com/24221107/108891299-8cc66800-75dc-11eb-9152-e559991a6e45.png)

**Comment by Noahmuiruri** [comment]
no the above setting is just to limit amount of depth for cast rays in the scene and not for specific material
![download](https://user-images.githubusercontent.com/29056816/108900406-a4c4d880-762a-11eb-8377-34858aef088f.png)

**Comment by osiriswrecks** [comment]
Oh gotchya. Sure thing we can add it to the list.
