### ISSUE TITLE
Assigning Materials at Object Level Doesn't Work

### ISSUE THREAD

**Issue by AlexeyAdamitsky** [lunadigital/btoa#78]
Blender 2.91.2
BtoA RC2 Branch 605a6ee
Arnold SDK 6.1.0
Windows 10 2004

If you assign materials at object level (1) they should override materials assigned at mesh level.
![image](https://user-images.githubusercontent.com/64398828/109203100-cce04300-77b4-11eb-8361-9c125b106671.png)

Monkeys should have all the same yellow plastic material. Currently doesn't work.
![image](https://user-images.githubusercontent.com/64398828/109203377-2183be00-77b5-11eb-95ca-8dbf0d3a3f94.png)

Here is a test scene:
[Arnold_Materials_Test.zip](https://github.com/lunadigital/btoa/files/6045191/Arnold_Materials_Test.zip)

**Comment by osiriswrecks** [comment]
@AlexeyAdamitsky Ready for testing!

**Comment by AlexeyAdamitsky** [comment]
It works now. Thank you.
