### ISSUE TITLE
Materials Assignment Bug Produces Transparent Renders

### ISSUE THREAD

**Issue by AlexeyAdamitsky** [lunadigital/btoa#81]
Blender 2.92
BtoA Dev Branch e5dd725
Arnold SDK 6.1.0
Windows 10 2004

I've been experiencing a bug with materials assignment that produces transparent renders. It has been happening for a while now but I couldn't spot why it's happening. Seems a bit random to me but I'm sure it's not.

Here is a scene created from scratch. Once the scene is ready I assign and setup some basic materials.
![image](https://user-images.githubusercontent.com/64398828/109467470-46f61d80-7a7c-11eb-89d7-f8f07f97ac19.png)

With the first render we see the bug. The background (**2**) and the pedestal (**1**) are rendered as transparent objects or aren't rendered at all I'm not sure what is happening here.
![image](https://user-images.githubusercontent.com/64398828/109467658-91779a00-7a7c-11eb-920e-2523a01d4fed.png)

Only changing the names of objects that generates issues to anything else helps to solve the issue.
![image](https://user-images.githubusercontent.com/64398828/109467952-01862000-7a7d-11eb-9e5d-afea403978ca.png)

Now scene renders as expected.
![image](https://user-images.githubusercontent.com/64398828/109468012-12369600-7a7d-11eb-9a08-e166f3fb39da.png)

I attached the scene with the issue described above. To see how issue I'm experiencing with transparent objects you need to remove **.BUG** (including dot) in the names of two objects I mentioned above:
[Arnold_Test_Scene.zip](https://github.com/lunadigital/btoa/files/6059912/Arnold_Test_Scene.zip)

**Comment by osiriswrecks** [comment]
@AlexeyAdamitsky This sounds similar to an issue I was having yesterday. Essentially, materials that existed in the Arnold Universe already weren't being applied properly. Can you download the latest `alpha-rc3` and test again?

**Comment by AlexeyAdamitsky** [comment]
Ok, I think I figured out what is causing the issue here. I'm testing it on the latest RC3 2a1b41d branch.

If I reproduce the bug the render won't even start with the latest build. Using the **same** name for an object and material causing the issue. Changing one or the other will stop causing issues and render will run fine.

![image](https://user-images.githubusercontent.com/64398828/109771579-075f3b00-7c0e-11eb-976f-c2d7561e36db.png)

**Comment by osiriswrecks** [comment]
AHA! I know what the problem is. Because the node names are the same for both it's basically skipping the second object because it thinks it's the same thing. We'll have to add another level of specificity to the unique name we generate to separate them.

**Comment by osiriswrecks** [comment]
@AlexeyAdamitsky This issue should be fixed. When you get a chance can you confirm?

**Comment by AlexeyAdamitsky** [comment]
Yes, I checked and I can't reproduce the bug anymore. Thank you.
