### ISSUE TITLE
Camera: DOF is Not Working

### ISSUE THREAD

**Issue by AlexeyAdamitsky** [lunadigital/btoa#82]
Blender 2.92
BtoA Dev Branch e5dd725
Arnold SDK 6.1.0
Windows 10 2004

I've been testing the DOF and it looks like it doesn't work. **Focus Distance** is set on the red monkey (**1**) and everything behind red monkey (**2**) should be out of focus.

![image](https://user-images.githubusercontent.com/64398828/109553605-472a0380-7ae4-11eb-91fe-d6ae9e6e9f19.png)

![image](https://user-images.githubusercontent.com/64398828/109554058-d0413a80-7ae4-11eb-94f8-f618d37396a9.png)

Test scene:
[Arnold_Test_Scene_Camera_DOF.zip](https://github.com/lunadigital/btoa/files/6064234/Arnold_Test_Scene_Camera_DOF.zip)

**Comment by osiriswrecks** [comment]
@AlexeyAdamitsky What are your DOF settings? Aperture size must be > 0 for Arnold to render any DOF.

**Comment by AlexeyAdamitsky** [comment]
I know. Nothing changes with any aperture > 0. You can run my scene and test. I couldn't make it work. I might be missing something but I think I tried all available approaches to activate/control it.

**Comment by AlexeyAdamitsky** [comment]
Turned out it was my error in testing. DOF is working fine.
