### ISSUE TITLE
Camera: DOF is Always On Bug

### ISSUE THREAD

**Issue by AlexeyAdamitsky** [lunadigital/btoa#85]
Blender 2.92
BtoA RC3 Branch 2a1b41d
Arnold SDK 6.1.0
Windows 10 2004

Disabling DOF for camera isn't working. It's still using it when it's ticked off. Currently the only way to disable it is to set Aperture Size to 0.

![uSkUMIh7OH](https://user-images.githubusercontent.com/64398828/109772701-5b1e5400-7c0f-11eb-8998-180132120948.gif)

**Comment by osiriswrecks** [comment]
@AlexeyAdamitsky This should now be fixed.

**Comment by AlexeyAdamitsky** [comment]
It's fixed now. Thank you.
