### ISSUE TITLE
Camera: DOF - Zero Focus Distance Crashes Render

### ISSUE THREAD

**Issue by AlexeyAdamitsky** [lunadigital/btoa#86]
Blender 2.92
BtoA RC3 Branch 2a1b41d
Arnold SDK 6.1.0
Windows 10 2004

If you set **Focus Distance** to **0** (1) while **Aperture Size** is anything than **0** (2) render won't start.
![image](https://user-images.githubusercontent.com/64398828/109773357-29f25380-7c10-11eb-8dc9-a5f67462c47b.png)

**Comment by osiriswrecks** [comment]
Believe it or not, I think this is "expected behavior". Cycles also renders a transparent frame for me if DOF is enable and focus distance is 0. We could either go one of two ways here: either render with no depth-of-field if focus distance is 0, or put an artificial floor at 0.0001 or some small value so it at least renders *something*. Thoughts @AlexeyAdamitsky?

**Comment by AlexeyAdamitsky** [comment]
It makes sense. It's probably an edge case scenario where a user would set Focus Distance at 0.

Although, I believe the better behavior would be to threat Focus Distance with 0 value setup as a DOF switch off parameter. You'd still keep DOF on if it was activated but if Focus Distance is at 0 you'd treat DOF as off internally. It would be much better if the render still works because currently it can confuse since it might not be obvious what went wrong if you left DOF active but set Focus Distance at 0.

I think it would be a better use experience. If a user was expecting to have DOF in the scene he'll go back to this parameter for troubleshooting and most likely will notice that Focus Distance is at 0. But if he gets a blank render he might be confused and start looking for a solution in some other places.

@osiriswrecks Let me know what you think.

**Comment by osiriswrecks** [comment]
@AlexeyAdamitsky From another perspective, what if someone wanted to animate the DOF from 0 to an "in-focus" value? Would it be weird to have it be perfectly in focus at 0 and then immediately disappear? I imagine I'd rather it slowly unblur and fade in so you at least understand what's happening, right?

**Comment by AlexeyAdamitsky** [comment]
@osiriswrecks Yes, makes sense. I didn't think about it because I don't do animation. But you're right I think it would be much better in your scenario.

**Comment by osiriswrecks** [comment]
Ok we'll leave the functionality as-is for now.
