### ISSUE TITLE
Lights: Issue When Light is Viewed On Camera

### ISSUE THREAD

**Issue by AlexeyAdamitsky** [lunadigital/btoa#95]
Blender 2.92
BtoA RC3 Branch d4a1ca0
Arnold SDK 6.1.0
Windows 10 2004

When previewing lights with **Visibility Camera** enabled the **Roundness** and **Soft Edge** isn't visible when viewed directly. It's only visible in reflections with correct settings. I don't believe it's an expected behavior.

The lights in the scene are instances of the same light. Light 1 is the reflection of the light. Light 2 is the light that is faced to the camera. The light 2 should be the same as light 1.
![image](https://user-images.githubusercontent.com/64398828/111682509-828f3680-8835-11eb-8787-5f4b74a78d31.png)

Have a look at the attached scene file.
[Arnold_Test_Scene_Lights_Check.zip](https://github.com/lunadigital/btoa/files/6166631/Arnold_Test_Scene_Lights_Check.zip)

**Comment by osiriswrecks** [comment]
I believe this is expected behavior but I'll have to check in Gaffer. As far as the API is concerned there is no difference between reflections and camera visibility for these settings.

**Comment by AlexeyAdamitsky** [comment]
I think you might be right that it's an expected behavior. I can't find any proofs that it isn't. It's not what I would expect though but it's fine.

The only time when you can see the actual "shape" of the lights is when you're using textures for the lights. I'll leave it up to you to decide if it warrants any further investigations or if it should be closed.

**Comment by AlexeyAdamitsky** [comment]
Sorry, closed it accidentally myself. Leave it up to you tough to decide on this.

**Comment by osiriswrecks** [comment]
Ha, no worries. I'll test it this weekend but won't consider it a priority for the upcoming alpha release. Thanks for bringing it up.

**Comment by osiriswrecks** [comment]
I just confirmed this as expected behavior with Arnold in Gaffer - closing out.
